// Global
export const URL = process.env.REACT_APP_API_URL;
export const RESET_DATA = "RESET_DATA";
export const SET_ERROR = "SET_ERROR";
export const SET_LOADING = "SET_LOADING";
export const SET_SUCCESS = "SET_SUCCESS";
export const RESET_GLOBAL_DATA = "RESET_GLOBAL_DATA";

// ToDo && SingleTask
export const TOGGLE_EDIT = "TOGGLE_EDIT";
export const SET_TASKS = "SET_TASKS";
export const DELETE_TASK = "DELETE_TASK";
export const SET_FILTEREDTASKS = "SET_FILTEREDTASKS";
export const TOGGLE_CHECKED = "TOGGLE_CHECKED";
export const SET_ISOPENMODAL = "SET_ISOPENMODAL";
export const ADD_TASK = "ADD_TASK";
export const SET_TASKINFO = "SET_TASKINFO";
export const SET_ISOPENCONFIRMMODAL = "SET_ISOPENCONFIRMMODAL";
export const SET_EDITABLETASK = "SET_EDITABLETASK";
export const EDIT_TASK = "EDIT_TASK";
export const SET_SINGLETASK = "SET_SINGLETASK";
export const DELETE_CHECKED_TASKS = "DELETE_CHECKED_TASKS";
export const TOGGLE_ALL_CHECKED = "TOGGLE_ALL_CHECKED";

// Contact
export const SET_FORMDATA = "SET_FORMDATA";
export const RESET_CONTACT_DATA = "RESET_CONTACT_DATA";

// TaskModal
export const CHANGE_MODAL_FORM = "CHANGE_MODAL_FORM";
export const SET_DATE = "SET_DATE";
export const RESET_MODAL_DATA = "RESET_MODAL_DATA";
export const SET_INITIALSTATE = "SET_INITIALSTATE";
export const SUBMIT_MODAL_FORM = "SUBMIT_MODAL_FORM";

//Navbar
export const CHANGE_NAVBAR_DIRECTION = "CHANGE_NAVBAR_DIRECTION";
export const SET_CLICK = "SET_CLICK";
export const RESET_NAVBAR_DATA = "RESET_NAVBAR_DATA";

//Search
export const CHANGE_SEARCH_VALUE = "CHANGE_SEARCH_VALUE";
export const TOGGLE_CLICK = "TOGGLE_CLICK";
export const SET_DROPDOWN_VALUE = "SET_DROPDOWN_VALUE";
export const SET_DATEPICKER_DATE = "SET_DATEPICKER_DATE";
export const SORT_FILTER_TASKS = "SORT_FILTER_TASKS";
export const RESET_SEARCH_DATA = "RESET_SEARCH_DATA";
